parameters:
- name: dependsOnJob
  type: string
- name: tenantResourceGroupName
  type: string
- name: storageAccountResourceGroup
  type: string
- name: storageAccount
  type: string
- name: storageAccountContainerName
  type: string
- name: appServiceName
  type: string
- name: webAppName
  type: string
- name: configureBackup
  type: boolean
  default: true

resources:
  repositories:
  - repository: foundationAzure
    type: git    
    name: Custom/foundation-azure
    ref: ${{ foundationAzureBranchRef }}

jobs:
- job: ConfigureBackup
  dependsOn: ${{ dependsOnJob }} # CreateAppService
  condition: or(and(succeeded(), eq(${{ parameters.configureBackup }}, true), and(eq(${{ parameters.createAppService }}, false), eq(${{ parameters.configureBackup }}, true) # only run if AppService was created and configuration is true
  #condition: succeeded() # only run if AppService was created and configuration is true
  pool:
    name: ${{ poolName }}
  
  variables:
    NonProdStorageAccountName: 'ctstore'
    StorageAccountContainerName: 'web-app-backups'
    DevAppServiceName: 'dev-test'

  steps:
  - checkout: foundationAzure
    clean: true
  
  - powershell: |
      Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
      Install-Module -Name AzureRM -Force -Scope CurrentUser -AllowClobber    
    displayName: 'Install AzureRM Modules'

  - task: PowerShell@2
    displayName: 'Enable App Service Backup'
    inputs:
      targetType: filePath
      filePath: './$(System.DefaultWorkingDirectory)/ExecuteAzureRmAppServiceBackup.ps1'
      arguments: '-ResourceGroupName "$(DevEastTenantResourceGroup)" -StorageAccountResourceGroupName "$(NonProdStorageAccountResourceGroupName)" -StorageAccountName "$(NonProdStorageAccountName)" -StorageAccountContainerName "$(StorageAccountContainerName)" -WebAppName "$(DevAppServiceName)" -BackupName "$(DevAppServiceName)" -ServicePrincipalID "$(AzureNonProdAppId)" -ServicePrincipalKey "$(AzureNonProdSecret)" -Tenant $(AzureNonProdTenantId) -Subscription $(AzureNonProdSubscriptionId)'

  - task: PowerShell@2
    displayName: 'Schedule App Service Backup'
    inputs:
      targetType: filePath
      filePath: './$(System.DefaultWorkingDirectory)/ExecuteScheduleDailyAppServiceBackupForSingleAppService.ps1'
      arguments: '-ResourceGroupName "$(DevEastTenantResourceGroup)" -StorageAccountResourceGroupName "$(NonProdStorageAccountResourceGroupName)" -StorageAccountName "$(NonProdStorageAccountName)" -StorageAccountContainerName "$(StorageAccountContainerName)" -WebAppName "$(DevAppServiceName)" -StartHour "$(StartHour)" -RetentionPeriodInDays "$(RetentionPeriodInDays)" -ServicePrincipalID "$(AzureNonProdAppId)" -ServicePrincipalKey "$(AzureNonProdSecret)" -Tenant $(AzureNonProdTenantId) -Subscription $(AzureNonProdSubscriptionId)'
