parameters:
- name: resourceGroupName
  type: string
- name: templateFileName
  type: string
- name: templateParametersFileName
  type: string
- name: configureBackup
  type: boolean
- name: poolName
  type: string
  default: VS2017
- name: repoAlias
  type: string
- name: connectedServiceNameARM
  type: string
- name: foundationAzureBranchRef
  type: string
- name: createAppService
  type: boolean
  default: true

resources:
  repositories:
  - repository: foundationAzure
    type: git    
    name: Custom/foundation-azure
    ref: ${{ foundationAzureBranchRef }}

jobs:
- job: CreateAppService
    
  pool:
    name: ${{ poolName }}

  steps:  
  - checkout: foundationAzure
    clean: true

  - task: AzurePowerShell@1
    condition: eq(${{ parameters.createAppService }}, true)
    displayName: 'Create App Service'
    inputs:
      ConnectedServiceNameSelector: ConnectedServiceNameARM
      ConnectedServiceNameARM: ${{ connectedServiceNameARM }} 
      ScriptPath: '$(System.DefaultWorkingDirectory)/AppService/Deploy-Azure-AppService.ps1'
      ScriptArguments: '-ResourceGroupName "${{ resourceGroupName }}" -TemplateFileName "${{ templateFileName }}" -TemplateParametersFileName "${{ templateParametersFileName }}"'

